[tool.ruff]
line-length = 120
target-version = "py310" # since PYTHON_VERSION=python3.10 in base/Dockerfile
select = ["E", "F", "FLY", "ICN", "Q", "RUF", "UP", "W"]

[tool.ruff.pycodestyle]
max-doc-length = 120

[tool.ruff.pydocstyle]
convention = "numpy"
