name: CI

on:
  push:
    branches:
      - "**"
      - "!**-update-20**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip -q install --break-system-packages --upgrade ruff yamllint
      - name: Run ruff on python files
        run: |
          python3 -m ruff check .
      - name: Run yamllint
        run: |
          python3 -m yamllint -d "{extends: default, rules: {document-start: {present: false}, line-length: disable, truthy: {check-keys: false}}}" .
