name: CI

on:
  push:
    branches:
      - "**"
      - "!**-update-20**"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip3 -q install --upgrade flake8 Flake8-pyproject
      - name: Run flake8 checks
        run: |
          flake8 .
